version: "3"
services:
  nuxt:
    build:
      context: .
      dockerfile: ./build/nuxt/Dockerfile
      args:
        - APPNAME=myapp
    ports:
      - "3000:3000"
    volumes:
      - "./nuxt/app:/app"
    tty: true
    stdin_open: true